name: Daily H1B Data Scraper

on:
  schedule:
    - cron: '0 16 * * *'  # every day at 9:00 UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python h1b_scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/h1b_companies.csv docs/salary_distribution.png
        git commit -m "Auto-update H1B data and visualization"
        git push origin main