name: Daily H1B Data Scraper

on:
  schedule:
    - cron: '0 16 * * *'  # Los Angeles 9:00 AM (UTC-7/8)
  workflow_dispatch:     # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Create directories
      run: |
        mkdir -p data
        mkdir -p docs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python h1b_scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A  # add all changes
        git diff --staged --quiet || (git commit -m "Auto-update H1B data and visualization" && git push origin main) 